### ISSUE TITLE
Skapa profiler

### ISSUE THREAD

**Issue by rickardaa** [Sundbybergs-IT/Crom-Fortune#55]
Det borde gå att skapa upp profiler för flera olika aktieportföljer.

**Comment by alwa** [comment]
Var vill du lägga till nya profiler? :stuck_out_tongue_winking_eye:

**Comment by rickardaa** [comment]
På ett bra ställe. Prio 1 för denna funktion!

**Comment by alwa** [comment]
Frääääs
